[project]
name = "idealfullbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "alembic>=1.17.2",
    "asyncpg>=0.31.0",
    "pydantic-settings>=2.12.0",
    "sqlalchemy>=2.0.44",
]
